services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: db
      DB_NAME: $DB_NAME
      OLLAMA_URL: $OLLAMA_URL
      OLLAMA_USER: $OLLAMA_USER
      OLLAMA_PASS: $OLLAMA_PASS
      OLLAMA_MODEL: $OLLAMA_MODEL

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      VITE_API_TARGET: $VITE_API_TARGET

  db:
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_vol:/var/lib/postgresql

volumes:
  postgres_vol: